title: "Faiaz Amin Khan"
name: "Faiaz Amin Khan"
description: "I research and build systems that span the physical-digital divide. From designing patent-grade acoustic sensors at Samsung R&D to deploying agentic AI workflows, my work focuses on decoding human signals to create seamless, intelligent interactions."
url: "https://faiazamin.github.io"
baseurl: "" # keep empty for user site; set to repo name only if deploying under a subpath

# Minimal Mistakes settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"  # you can try "air", "plum", "contrast", etc.

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Site author
author:
  name: "Faiaz Amin Khan"
  avatar: "/assets/img/my_img.jpeg" # add later if you want
  bio: "I research and build systems that span the physical-digital divide. From designing patent-grade acoustic sensing mechanism at Samsung R&D to deploying AI workflows in resource contrained device, my work focuses on decoding human signals to create seamless, intelligent interactions."
  location: "Dhaka, Bangladesh"
  email: "faiazamin443@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/faiazamin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/faiaz-amin-khan-05581a179/"
    - label: "CV"
      icon: "far fa-file-alt"
      url: "/assets/Faiaz_CV_PhD.pdf"

# Navigation
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "projects"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - _pages

permalink: /:categories/:title/
